# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faead166d0b05f3fe16a7d84d5e9816b08cbfdd3287b1b523c331dd9dc8bbf3475a86720cfd5a41d6e2940b102d477cbf4e46fe5786efa1ff2995cb219117755

test:
  secret_key_base: c79972d892edc6cafb5278477762902ccc66680cb7d9b4f5e2c3718a02bf5af27e9d99d7062c9f268c7ece56409044a642cde7477f0a50e75b0c8083e4bdbde3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
